apiVersion: v1
kind: Namespace
metadata:
  name: vllm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache
  namespace: vllm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  # FIX: Switched to the 'standard' StorageClass which uses Immediate binding.
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-llama3
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-llama3
  template:
    metadata:
      labels:
        app: vllm-llama3
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      imagePullSecrets:
        - name: rh-pull

      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

      initContainers:
        - name: fix-cache-perms
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command: ["/bin/sh", "-c", "mkdir -p /home/vllm/.cache && chown -R 1000:1000 /home/vllm/.cache"]
          volumeMounts:
            - name: cache
              mountPath: /home/vllm/.cache
          securityContext:
            runAsUser: 0

      containers:
        - name: vllm
          image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:v0.4.3-1
          args:
            - "--model"
            - "meta-llama/Meta-Llama-3-8B-Instruct"
            - "--tensor-parallel-size"
            - "1"
            - "--port"
            - "8000"
            - "--gpu-memory-utilization"
            - "0.90"
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HUGGING_FACE_HUB_TOKEN
            - name: HF_HOME
              value: "/home/vllm/.cache"
          securityContext:
            runAsUser: 0
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: cache
              mountPath: /home/vllm/.cache
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: vllm-cache
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama3-service
  namespace: vllm
spec:
  type: LoadBalancer
  selector:
    app: vllm-llama3
  ports:
    - name: http
      port: 80
      targetPort: http
      