apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: {{ .Values.nameSpace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.litellm.replicas }}
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: {{ .Values.litellm.image }}
          args: ["--config", "/etc/litellm/config.yaml", "--port", "{{ .Values.litellm.port }}"]
          env:
            {{- range .Values.litellm.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/litellm
          ports:
            - containerPort: {{ .Values.litellm.port }}
      volumes:
        - name: config
          configMap:
            name: litellm-config
            items:
              - key: config.yaml
                path: config.yaml
