apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-gpu-prod
  region: us-east-1
  version: "1.33"

iam:
  withOIDC: true

# Use only 1d + 1f subnets so the control plane avoids 1e
vpc:
  id: vpc-0c5b87e00f328a749
  subnets:
    private:
      us-east-1d: { id: subnet-0c9644ba720873e29 } # private 1d
      us-east-1f: { id: subnet-019932a6fa140b2e8 } # private 1f
    public:
      us-east-1d: { id: subnet-0236bf8e61a22de72 } # public 1d
      us-east-1f: { id: subnet-06bcdfa0f633356f5 } # public 1f

managedNodeGroups:
  - name: cpu-ng
    instanceType: m6i.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    amiFamily: AmazonLinux2023   # required for EKS 1.33
    privateNetworking: true
    volumeSize: 100
    subnets:                      # keep workers in 1d + 1f as well
      - subnet-0c9644ba720873e29  # private 1d
      - subnet-019932a6fa140b2e8  # private 1f

cloudWatch:
  clusterLogging:
    enableTypes: ["api","audit","authenticator","controllerManager","scheduler"]
    